### ISSUE TITLE
[STRATEGY REQUEST]

### ISSUE THREAD

**Issue by regholl** [kieran-mackle/autotrader-demo#5]
[strat2.txt](https://github.com/kieran-mackle/autotrader-demo/files/8050653/strat2.txt)
**Describe the strategy you'd like to see added**
A clear and concise description of the strategy, including entry and exits conditions, position sizing, indicators, etc.

**Is your strategy request related to one posted online somewhere? Please provide any links.**
A clear and concise description of where you found the strategy.

**Additional context**

**Comment by kieran-mackle** [comment]
This strategy has already been implemented - it is the `ema_crossover` strategy, but using simple moving averages instead of exponential moving averages.
