### ISSUE TITLE
[Broker wishlist] Support for alpaca?

### ISSUE THREAD

**Issue by onionhammer** [kieran-mackle/autotrader-demo#9]
Alpaca is a broker that is designed to be "api-first", so it should be relatively straightforward to plug in. I'm still learning the codebase so I may take a stab at implementing it; if it's general enough I'll contribute it back

https://alpaca.markets/docs/

**Comment by kieran-mackle** [comment]
Please re-open this issue in the [main AutoTrader repository](https://github.com/kieran-mackle/AutoTrader).
